{
  "msg": "Failed Operation",
  "code": "500",
  "success": false,
  "eventId": "mjhngtfrew",
  "error": {
    "typee": "SERVER_ERROR",
    "title": "Internal Server Error",
    "details": "The Server Encountered an unaccepted Condition which prevented from fulfilling the request"
  }
}