{
  "msg": "Failed Operation",
  "code": "400",
  "success": false,
  "eventId": "mjhngtfrew",
  "error": {
    "typee": "BAD_REQUEST",
    "title": "Invalid Request",
    "details": "Input Contains Invalid Data"
  }
}