{
  "msg": "Failed Operation",
  "code": "401",
  "success": false,
  "eventId": "mjhngtfrew",
  "error": {
    "typee": "UNAUTHORIZED",
    "title": "Unauthorized Request",
    "details": "This Requires All Requests To Be Authenticated"
  }
}