{
  "msg": "Failed Operation",
  "code": "404",
  "success": false,
  "eventId": "mjhngtfrew",
  "error": {
    "typee": "NOT_FOUND",
    "title": "Resource Not Found",
    "details": "The URI Requested Is Invalid or the resource requested does not exists"
  }
}