#%RAML 1.0 Trait

headers:
  x-cms-transactionId:
    type: string
    required: true
    minLength: 36
    maxLength: 36
    example: "jfhuyuijtr-jjfurhjkrk-kjyhtgkjgg-mnh"
  clientId:
    type: string
    required: true
    example: "mjhnbgtrfdesaqwuiol"
  clientSecret:
    type: string
    required: true
    example: "mkjhnbgtfrsedwsuiqo"